/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Проверка того, что процесс жив. Не проверяет зависимости.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Проверка готовности принимать трафик (БД, Redis доступны).
         */
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/currencies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список валют */
        get: operations["listCurrencies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/directions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список направлений */
        get: operations["listDirections"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exchangers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список обменников */
        get: operations["listExchangers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exchangers/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Карточка обменника */
        get: operations["getExchanger"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rates/{direction}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Курсы по направлению
         * @description Текущие курсы обменников по направлению, лучший — первым.
         */
        get: operations["getRates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rates/{direction}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Поток обновлений курсов (SSE)
         * @description Server-Sent Events. Каждое событие `rates` содержит актуальный
         *     массив `RateRow` по направлению. Курсы обновляются на сервере
         *     и пушатся сюда без опроса.
         */
        get: operations["streamRates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /**
             * @example ok
             * @enum {string}
             */
            status: "ok";
        };
        Readiness: {
            /** @enum {string} */
            status: "ok" | "degraded";
            /**
             * @example {
             *       "postgres": "ok",
             *       "redis": "ok"
             *     }
             */
            checks: {
                [key: string]: string;
            };
        };
        Error: {
            /**
             * @description Машиночитаемый код ошибки
             * @example not_found
             */
            code: string;
            /** @description Человекочитаемое сообщение */
            message: string;
            /** @description Дополнительный контекст ошибки */
            details?: {
                [key: string]: unknown;
            };
        };
        Pagination: {
            /** Format: int64 */
            total: number;
            limit: number;
            offset: number;
        };
        /**
         * @description Тип валюты
         * @enum {string}
         */
        CurrencyKind: "crypto" | "fiat" | "cash";
        Currency: {
            /** Format: uuid */
            id: string;
            /**
             * @description Тикер/код валюты
             * @example BTC
             */
            code: string;
            /** @example Bitcoin */
            name: string;
            kind: components["schemas"]["CurrencyKind"];
            /**
             * @description Сеть для крипты (TRC20, ERC20 и т.п.)
             * @example TRC20
             */
            network?: string | null;
            /** Format: uri */
            iconUrl?: string | null;
        };
        Direction: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            fromCurrencyId: string;
            /** Format: uuid */
            toCurrencyId: string;
            /** @example usdt-tinkoff */
            slug: string;
            /** @example USDT */
            fromCode: string;
            /** @example Tether */
            fromName: string;
            /** @example TINKOFF */
            toCode: string;
            /** @example Тинькофф */
            toName: string;
            isPopular: boolean;
        };
        /** @enum {string} */
        ExchangerStatus: "active" | "paused" | "banned";
        Exchanger: {
            /** Format: uuid */
            id: string;
            /** @example cryptobridge */
            slug: string;
            /** @example CryptoBridge */
            name: string;
            status: components["schemas"]["ExchangerStatus"];
            /** @description Есть партнёрское размещение (реферальная ссылка) */
            partner: boolean;
            isVerified: boolean;
            reviewsCount: number;
            /** Format: float */
            ratingAvg?: number | null;
            /** Format: uri */
            websiteUrl?: string | null;
            /** Format: uri */
            logoUrl?: string | null;
            description?: string | null;
            /** @description Суммарный резерв по активным курсам (decimal-строкой), null если курсов нет */
            reserveTotal?: string | null;
            /** @description Число направлений с активным курсом */
            directionsCount: number;
            /** @description Торгуемые исходные валюты (коды), напр. USDT, BTC */
            assets: string[];
            /** @description Год добавления обменника на Kurso */
            onSince: number;
        };
        /** @description Курс конкретного обменника по направлению (денормализовано для выдачи). */
        RateRow: {
            /** Format: uuid */
            exchangerId: string;
            exchangerSlug: string;
            exchangerName: string;
            partner: boolean;
            /** Format: float */
            ratingAvg?: number | null;
            reviewsCount: number;
            /**
             * @description Курс decimal-строкой
             * @example 81.20
             */
            rate: string;
            reserve?: string | null;
            minAmount?: string | null;
            maxAmount?: string | null;
            /** Format: date-time */
            fetchedAt: string;
        };
        RatesResponse: {
            direction: components["schemas"]["Direction"];
            rates: components["schemas"]["RateRow"][];
        };
        Rate: {
            /** Format: uuid */
            exchangerId: string;
            /** Format: uuid */
            directionId: string;
            /**
             * @description Курс в виде decimal-строки (чтобы не терять точность)
             * @example 0.0000234
             */
            rate: string;
            /** @description Резерв в валюте назначения (decimal-строка) */
            reserve?: string | null;
            minAmount?: string | null;
            maxAmount?: string | null;
            /** Format: date-time */
            updatedAt: string;
        };
    };
    responses: {
        /** @description Ошибка */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Сервис жив */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Сервис готов */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
            /** @description Сервис не готов */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
        };
    };
    listCurrencies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список валют */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Currency"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listDirections: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список направлений */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Direction"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listExchangers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список обменников */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Exchanger"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getExchanger: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Обменник */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Exchanger"];
                };
            };
            404: components["responses"]["Error"];
            default: components["responses"]["Error"];
        };
    };
    getRates: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Слаг направления, например usdt-tinkoff */
                direction: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Курсы по направлению */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RatesResponse"];
                };
            };
            404: components["responses"]["Error"];
            default: components["responses"]["Error"];
        };
    };
    streamRates: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                direction: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Поток событий SSE */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
        };
    };
}
