/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Проверка того, что процесс жив. Не проверяет зависимости.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Проверка готовности принимать трафик (БД, Redis доступны).
         */
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/currencies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Список валют
         * @description Справочник валют. Полноценно реализуется на этапе 1.
         */
        get: operations["listCurrencies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /**
             * @example ok
             * @enum {string}
             */
            status: "ok";
        };
        Readiness: {
            /** @enum {string} */
            status: "ok" | "degraded";
            /**
             * @example {
             *       "postgres": "ok",
             *       "redis": "ok"
             *     }
             */
            checks: {
                [key: string]: string;
            };
        };
        Error: {
            /**
             * @description Машиночитаемый код ошибки
             * @example not_found
             */
            code: string;
            /** @description Человекочитаемое сообщение */
            message: string;
            /** @description Дополнительный контекст ошибки */
            details?: {
                [key: string]: unknown;
            };
        };
        Pagination: {
            /** Format: int64 */
            total: number;
            limit: number;
            offset: number;
        };
        /**
         * @description Тип валюты
         * @enum {string}
         */
        CurrencyKind: "crypto" | "fiat" | "cash";
        Currency: {
            /** Format: uuid */
            id: string;
            /**
             * @description Тикер/код валюты
             * @example BTC
             */
            code: string;
            /** @example Bitcoin */
            name: string;
            kind: components["schemas"]["CurrencyKind"];
            /**
             * @description Сеть для крипты (TRC20, ERC20 и т.п.)
             * @example TRC20
             */
            network?: string | null;
            /** Format: uri */
            iconUrl?: string | null;
        };
        Direction: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            fromCurrencyId: string;
            /** Format: uuid */
            toCurrencyId: string;
            /** @example btc-to-usdt-trc20 */
            slug: string;
            /** @default false */
            isPopular: boolean;
        };
        /** @enum {string} */
        ExchangerStatus: "active" | "paused" | "banned";
        Exchanger: {
            /** Format: uuid */
            id: string;
            /** @example fastchange */
            slug: string;
            /** @example FastChange */
            name: string;
            status: components["schemas"]["ExchangerStatus"];
            /** Format: float */
            ratingAvg?: number | null;
            /** Format: uri */
            websiteUrl?: string | null;
        };
        Rate: {
            /** Format: uuid */
            exchangerId: string;
            /** Format: uuid */
            directionId: string;
            /**
             * @description Курс в виде decimal-строки (чтобы не терять точность)
             * @example 0.0000234
             */
            rate: string;
            /** @description Резерв в валюте назначения (decimal-строка) */
            reserve?: string | null;
            minAmount?: string | null;
            maxAmount?: string | null;
            /** Format: date-time */
            updatedAt: string;
        };
    };
    responses: {
        /** @description Ошибка */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Сервис жив */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Сервис готов */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
            /** @description Сервис не готов */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
        };
    };
    listCurrencies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список валют */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Currency"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
}
